### ISSUE TITLE
Underutilization?

### ISSUE THREAD

**Issue by genpfault** [CernKCChallenge/CernKCChallenge#1]
Got 32 logical cores in this box and BOINC is using...two.  Any way to boost that using a single instance of the standard Debian client?  `ncpus` in `cc_config.xml` is already `-1`; setting to `8` doesn't help, still just get two tasks.

**Comment by bdice** [comment]
I'll look into this and follow up!

**Comment by genpfault** [comment]
Actually I think I got it figured out, had to drop back to the non-Debian Boinc client and use separate data directories:

```
./boinc --allow_multiple_clients --gui_rpc_port 31417 --dir /some/dir/01
./boinc --allow_multiple_clients --gui_rpc_port 31418 --dir /some/dir/02
./boinc --allow_multiple_clients --gui_rpc_port 31419 --dir /some/dir/03
./boinc --allow_multiple_clients --gui_rpc_port 31420 --dir /some/dir/04
...
```

Use the XML snippet on the [auth key page](http://lhcathome2.cern.ch/vLHCathome/weak_auth.php):

```
<account>
    <master_url>http://lhcathome2.cern.ch/vLHCathome/</master_url>
    <authenticator>abcdef1234567890abcdef1234567890</authenticator>
</account>
```

...and stick that in a `account_lhcathome2.cern.ch_vLHCathome.xml` in each numbered data directory.  Make sure you use your real account key and not just the weak one, the VMs error out otherwise:

```
...
2016-07-01 23:50:47 (14871): Guest Log: [ERROR] Weak account key not supported. Please connect using the account key.
2016-07-01 23:50:47 (14871): Guest Log: [INFO] Shutting Down.
2016-07-01 23:50:47 (14871): VM Completion File Detected.
2016-07-01 23:50:47 (14871): VM Completion Message: Weak account key not supported. Please connect using the account key.
...
```

Can't get `boincmgr` to talk to any of the clients but `boinccmd` works fine.
