### ISSUE TITLE
First set of CMS Simulations Failed with Disk Limit Error

### ISSUE THREAD

**Issue by wendelj** [CernKCChallenge/CernKCChallenge#2]
Got this error on the first set of CMS Simulation jobs. I think I followed the instructions on setting up everything correctly. Is there a setting I need to tweak somewhere?

Task 5964680:
Exit status: 196 (0xc4) EXIT_DISK_LIMIT_EXCEEDED
...
Peak disk usage: 8,183.16 MB

From event log:
7/1/2016 5:45:00 PM |  | Disk: 953.87 GB total, 605.33 GB free
7/1/2016 5:45:05 PM |  | max disk usage: 605.23GB
7/2/2016 5:47:24 PM | VirtualLHC@home | Aborting task CMS_7094_1467450282.545858_0: exceeded disk limit: 8183.16MB > 7629.39MB
7/2/2016 5:57:24 PM | VirtualLHC@home | Aborting task CMS_4244_1467447276.732148_0: exceeded disk limit: 7699.17MB > 7629.39MB

**Comment by bdice** [comment]
Hello, thanks for the detailed bug report! I have contacted the developers and will follow up with more information. In the meantime, try this. Go to Options > Computing Preferences > Disk and Memory. Under "Use no more than...", try setting the number higher. If your hard drive has plenty of space, try setting it to 100GB and then you can monitor the disk usage in the "Disk" tab (if you change BOINC to the Advanced View). Let us know if that helps. I may need to add a step to the setup procedure if this is a recurring problem.

**Comment by wendelj** [comment]
I currently don't have "Use no more than..." set. I only have "Leave at least" set to 1GB and "Use no more than" to 90% of total.

**Comment by bdice** [comment]
@wendelj I received a notice from one of the project developers. They were implementing a new workflow and made an error. They have now changed some settings that should reduce disk usage by saving (and uploading) fewer log files. Additionally, the job size has been reduced from 159k events to 100k. Hopefully, this should resolve the issue. Let us know if the problem continues - I'll close this issue for now.
