### ISSUE TITLE
Application list unclear...

### ISSUE THREAD

**Issue by genpfault** [CernKCChallenge/CernKCChallenge#3]
The [main page](https://cernkcchallenge.github.io/CernKCChallenge/) says to check  “CMS Simulations” and “Theory Simulations.”   But currently there's also a third option: `LHCb Simulations`.  Should all three be checked or just CMS & Theory Simulations?

**Comment by bdice** [comment]
Good question! LHCb is optional. Leaving LHCb unchecked will ensure that the gigabit-ready CMS jobs are performed for users with a sufficient internet connection. However, it is not problematic to have LHCb jobs enabled. The CMS jobs are intended for users with gigabit-speed internet. Theory simulations are a fall-back option in case gigabit-speed internet is not detected. I'll clarify this with more details from the CERN team.
